# https://stackoverflow.com/questions/72280771/how-to-use-secrets-when-building-docker-compose-locally
# https://docs.docker.com/build/building/secrets/#sources

services:
  app:
    build:
      context: .
      secrets:
        - my_secret
secrets:
  my_secret:
    file: ./my_secret.txt
